apiVersion: apps/v1
kind: Deployment
metadata:
  name: [APPLICATION_NAME]-deployment
  labels:
    app: [APPLICATION_NAME]
spec:
  replicas: [POD_COUNT]
  selector:
    matchLabels:
      app: [APPLICATION_NAME]
  template:
    metadata:
      labels:
        app: [APPLICATION_NAME]
    spec:
      containers:
      - name: [APPLICATION_NAME]-container
        image: [APPLICATION_IMAGE]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "[CPU]"
            memory: "[MEMORY]"
          # if limits defined, requests be the same by default (TODO: look after)
          requests:
            cpu: "[CPU]"
            memory: "[MEMORY]"
        ports:
        - containerPort: [APPLICATION_PORT]
        env:
        - name: ALLOC_HEAP_MB
          value: "2"
        - name: MAX_HEAP_SIZE_MB
          value: "300"
      nodeName: [WORKER_NODE] # if more worker node presented should use below:
      #nodeSelector:
        #type: worker
---
kind: Service
apiVersion: v1
metadata:
  name: [APPLICATION_NAME]-service
  labels:
    app: [APPLICATION_NAME]
spec:
  selector:
    app: [APPLICATION_NAME]
  ports:
  - protocol: TCP
    port: [APPLICATION_PORT]
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: nodejs-ingress-[ID]
#  namespace: default
#spec:
#  rules:
#  - host: nodejsapp-[ID]
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: nodejs-service-[ID]
#          servicePort: 80

