prometheus:
  deploy: "False"
  name: "prometheus"
  repo: "stable/prometheus"
  nspace: "metrics"  
  options:
    server.service.type: "NodePort"
    server.service.nodePort: "30000"

app:
  name: "redis"
  repo: "bitnami/redis"
  namespace: "default"
  options:
    master.service.nodePort: "30002"  # The range of valid ports is 30000-32767
    master.service.type: "NodePort"
    metrics.enabled: true      # Start a side-car prometheus exporter
  scale:  # parametrs can variable
    master.resources.limits.memory: ['256Mi', '256Mi']
    master.resources.limits.cpu:    ['100m',   '100m']
    slave.resources.limits.cpu:     ['100m',   '100m']
    cluster.slaveCount:             ['1',         '2']   

loader:
  name: "locust"
  # repo: "presslabs/locust"
  # repo: "stable/locust"
  repo: "/home/tutkovics/onlab_msc1/charts/stable/locust"  # install from local Chart
  namespace: "metrics"
  options:
    service.nodePort: "30001"
    worker.replicaCount: "20"
    master.config.target-host: "http://192.168.99.111:30002"
    worker.config.locust-script: "/locust-tasks/redis_locustfile.py"
  load:
    min_users: "0"
    max_users: "200"  # RPS = users x 10
    step: "10"
    time: "60"

cluster:
  ip: "192.168.99.111"
  name: "szakdoga" # configure kubectl in multicluster environment