develop:
  mode: "benchmark" # some functions need to call in different mode (eg: benchmark, develop)
  log_level: "debug" # can reduce log spams: warning level log
cluster:
  ip: "192.168.99.109"
  name: "minikube" # configure kubectl in multicluster environment (see: ~/.kube/config)
  worker_node:  "minikube" # worker node's name
  benchmark_node: "minikube"
prometheus:
  deploy: "True"
  node_port: "30000" # doesn't take effect
application:
  name: "apache-increment"
  image: "tuti/apache-benchmark:v1" # add explicit version number
  port: "80" # port to open in pods
benchmark:
  tool:
    name: "fortio"
    image: "fortio/fortio:1.3.1"
    port: "8080"
  time: "60" # benchmark run time
  qps_min: "0" # minimum requested qps
  qps_max: "4000" # maximum requested qps
  qps_granularity: "30" # granularity of qps
  # batch measurement
  pods: "1,2,3,4" # number of application pods in measurements
  cpu: "200m,200m,200m,200m" #, '100m', '100m', '100m']" # cpu limit / pod
  memory: "256Mi,256Mi,256Mi,256Mi" #, '64Mi', '64Mi', '64Mi']" # memory limit / pod
  save_results: "True" # save results to .json file
