develop:
  mode: "developp" # some functions need to call in different mode (eg: benchmark, develop)
  log_level: "debug"
cluster:
  ip: "192.168.99.107"
  name: "szakdoga" # configure kubectl in multicluster environment
  worker_node:  "minikube" # worker node's name
  benchmark_node: "minikube"
prometheus:
  deploy: "False"
  node_port: "30000" # doesn't take affect
application:
  name: "nginx-increment"
  image: "nginx:1.17" #nginx:latest
  port: "80" # port to open in pods
benchmark:
  tool:
    name: "fortio"
    image: "fortio/fortio:1.3.1" #fortio/fortio:latest_release
    port: "8080"
  time: "60" # benchmark run time
  qps_min: "0" # minimum requested qps
  qps_max: "6000" # maximum requested qps
  qps_granularity: "200" # granularity of qps
  # batch measurement
  pods: "1,2,3,4" #, '2', '3', '4']" # number of application pods in measurements
  cpu: "200m,200m,200m,200m,200m" #, '100m', '100m', '100m']" # cpu limit / pod
  memory: "64Mi,64Mi,64Mi,64Mi,64Mi" #, '64Mi', '64Mi', '64Mi']" # memory limit / pod
  save_results: "True" # save results to .json file
